version: '3.8'

services:

  mysql_8.3:
    container_name: mysql_8.3
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '33083:3306'
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_8.3_root_password
    secrets:
      - mysql_8.3_root_password
    volumes:
      - mysql_8.3:/var/lib/mysql

  mysql_8.2:
    container_name: mysql_8.2
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '33082:3306'
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_8.2_root_password
    secrets:
      - mysql_8.2_root_password
    volumes:
      - mysql_8.2:/var/lib/mysql

  mysql81:
    container_name: mysql_8.1
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '33081:3306'
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_8.1_root_password
    secrets:
      - mysql_8.1_root_password
    volumes:
      - mysql_8.1:/var/lib/mysql

  mysql80:
    container_name: mysql_8.0
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '33080:3306'
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_8.0_root_password
    secrets:
      - mysql_8.0_root_password
    volumes:
      - mysql_8.0:/var/lib/mysql

  mysql57:
    container_name: mysql_5.7
    image: mysql:5.7
    restart: always
    ports:
      - '33057:3306'
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_5.7_root_password
    secrets:
      - mysql_5.7_root_password
    volumes:
      - mysql_5.7:/var/lib/mysql

  mariadb_10.11:
    container_name: mariadb_10.11
    image: mariadb:10.11
    restart: always
    ports:
      - '31011:3306'
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_10.11_root_password
    secrets:
      - mariadb_10.11_root_password
    volumes:
      - mariadb_10.11:/var/lib/mysql
 
  mariadb_11.3:
    container_name: mariadb_11.3
    image: mariadb:11.3
    restart: always
    ports:
      - '3113:3306'
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_11.3_root_password
    secrets:
      - mariadb_11.3_root_password
    volumes:
      - mariadb_11.3:/var/lib/mysql


volumes:
  mysql_8.0:
  mysql_8.1:
  mysql_8.2:
  mysql_8.3:
  mysql_5.7:
  mariadb_10.11:
  mariadb_11.3:

secrets:
  mysql_8.3_root_password:
    file: ./secrets/mysql_8.3_root_password
  mysql_8.2_root_password:
    file: ./secrets/mysql_8.2_root_password
  mysql_8.1_root_password:
    file: ./secrets/mysql_8.1_root_password
  mysql_8.0_root_password:
    file: ./secrets/mysql_8.0_root_password
  mysql_5.7_root_password:
    file: ./secrets/mysql_5.7_root_password
  mariadb_10.11_root_password:
    file: ./secrets/mariadb_10.11_root_password
  mariadb_11.3_root_password:
    file: ./secrets/mariadb_11.3_root_password
